services:
  db:
    image: mongo:8.2.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: superuser
      MONGO_INITDB_ROOT_PASSWORD: superuser
      MONGO_INITDB_DATABASE: theFashionAppDB
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
